#!/bin/bash
echo "- A number of other enterpreters can be used in the shabang." 
echo "  Here are a number of examples"
echo "  Perl		/usr/bin/perl"
echo "  Ruby		/usr/bin/ruby"
echo "  Node.js	/usr/bin/node"
echo "  Php		/usr/bin/php"
echo "  Awk		/usr/bin/awk"
echo "  Sed		/usr/bin/sed"
echo "  Tcl		/usr/bin/tcl"
echo "  Lua		/usr/bin/lua"
echo "  R		/usr/bin/Rscript"
echo "  Zsh		/usr/bin/zsh"
echo "  Fish		/usr/bin/fish"
echo "  Groovy	/usr/bin/groovy"
echo "  Java		/usr/bin/jshell"
echo "  Scala		/usr/bin/scala"
echo "  python	/usr/bin/env python3"
echo "  C#		/usr/bin/env dotnet-script"
  
